### ISSUE TITLE
Sensors error in log

### ISSUE THREAD

**Issue by marhoy** [Sabuto/hassio-telegraf#16]
The add-on runs file and reports useful statistics to my Influxdb. But I get the following error in the log. Any way to fix the problem or disable the plugin?

My config looks like this:
```
{
  "influxDB": "http://10.0.1.202:8086",
  "influx_db": "telegraf",
  "kernel": {
    "enabled": false
  },
  "swap": {
    "enabled": true
  },
  "docker": {
    "enabled": false,
    "timeout": "5s"
  },
  "smart_monitor": {
    "enabled": false,
    "timeout": "30s"
  },
  "ipmi_sensor": {
    "enabled": false,
    "interval": "30s",
    "timeout": "20s",
    "server_user_id": "user",
    "server_password": "password",
    "server_protocol": "lan",
    "server_ip": "192.168.1.2"
  },
  "retention_policy": ""
}
```

# Logs
2019-11-24T13:55:50Z E! [inputs.sensors] Error in plugin: failed to run command /usr/bin/sensors -A -u: exit status 1 - No sensors found!
Make sure you loaded all the kernel drivers you need.
Try sensors-detect to find out which these are.

**Comment by Sabuto** [comment]
Another person reported this error too but I dont get it. How are you running hassio?

**Comment by marhoy** [comment]
I'm running the hass.io image (https://www.home-assistant.io/hassio/installation/) on a rpi3b.
Currently running supervisor 192, HassOS 2.12 and Home Assistant 0.102.0.

**Comment by balda** [comment]
I have the same problem with a fresh installed hass.io (same versions and same raspberry as @marhoy)

**Comment by Sabuto** [comment]
Ok, I am going to tray and make a dev branch, and work on a few things i'll let you know when pushed so you can try it out

**Comment by Sabuto** [comment]
please update to 0.5.1 and try that it should work using the thermal scraper

**Comment by mikebell** [comment]
I'm also seeing this on 0.5.4

```
2020-09-08T10:56:40Z E! [inputs.sensors] Error in plugin: failed to run command /usr/bin/sensors -A -u: exit status 1 - No sensors found!
Make sure you loaded all the kernel drivers you need.
Try sensors-detect to find out which these are.
```

Config

```
custom_conf:
  enabled: false
  location: /share/telegraf.conf
hostname: homeassistant
influxDB:
  enabled: true
  url: 'http://192.168.1.12:8086'
  db: homeassistant
  retention_policy: autogen
  username: ha
  password: *****************
kernel:
  enabled: true
swap:
  enabled: true
docker:
  enabled: true
  timeout: 5s
thermal:
  enabled: false
smart_monitor:
  enabled: false
  timeout: 30s
ipmi_sensor:
  enabled: false
  interval: 30s
  timeout: 20s
  server_user_id: user
  server_password: password
  server_protocol: lan
  server_ip: 192.168.1.2
influxDBv2:
  enabled: false
  url: 'http://127.0.0.1:9999'
  organization: ''
  token: ''
  bucket: ''
```
