### ISSUE TITLE
Fails to start: sed: -e expression #1, char 17: unknown option to `s'

### ISSUE THREAD

**Issue by sgofferj** [sabuto/hassio-telegraf#45]
# Type of Issue
Issue

# Description of issue
Addon fails to start

# Ideas to fix
None

# Logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] scripts: applying... 
[fix-attrs.d] scripts: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Telegraf
 An addon to add telegraf to hassio.
-----------------------------------------------------------
 Add-on version: 0.6.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.4  (aarch64 / raspberrypi3-64)
 Home Assistant Core: 2022.2.6
 Home Assistant Supervisor: 2022.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] telegraf.sh: executing... 
[10:49:21] INFO: Updating config
sed: -e expression #1, char 17: unknown option to `s'
[cont-init.d] telegraf.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
foreground: warning: unable to spawn s6-nuke: Permission denied
[s6-finish] sending all processes the KILL signal and exiting.
```

# Config
```
custom_conf:
  enabled: false
  location: /share/telegraf.conf
hostname: rpi3-2
influxDB:
  enabled: true
  url: https://influx.domain.com
  db: telegraf
  username: myusername
  password: mypassword
kernel:
  enabled: true
swap:
  enabled: true
docker:
  enabled: true
  timeout: 5s
thermal:
  enabled: true
smart_monitor:
  enabled: true
  timeout: 30s
ipmi_sensor:
  enabled: false
  interval: 30s
  timeout: 20s
  server_user_id: user
  server_password: password
  server_protocol: lan
  server_ip: 192.168.1.2
influxDBv2:
  enabled: false
  url: http://127.0.0.1:9999
  organization: ''
  token: ''
  bucket: ''
prometheus:
  enabled: false
  metrics_path: /metrics
```
